/**
 * MCP Server Catalog
 * Pre-configured MCP servers that can be installed with one click
 */

export interface McpServerDefinition {
  id: string;
  name: string;
  description: string;
  category: McpCategory;
  transport: "stdio" | "http" | "sse";
  command?: string;
  args?: string[];
  url?: string;
  env?: Record<string, string>;
  requiresAuth?: boolean;
  authType?: "api-key" | "oauth" | "token";
  authEnvVar?: string;
  documentation?: string;
  icon?: string;
  tags?: string[];
  popular?: boolean;
}

export type McpCategory = 
  | "filesystem"
  | "code"
  | "database"
  | "ai"
  | "productivity"
  | "cloud"
  | "security"
  | "widgetdc"
  | "custom";

export const MCP_SERVER_CATALOG: McpServerDefinition[] = [
  // ============ OFFICIAL / POPULAR ============
  {
    id: "filesystem",
    name: "Filesystem",
    description: "Read, write, and manage files on your system",
    category: "filesystem",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-filesystem", "."],
    icon: "📁",
    tags: ["files", "read", "write", "directory"],
    popular: true,
  },
  {
    id: "github",
    name: "GitHub",
    description: "Interact with GitHub repositories, issues, and PRs",
    category: "code",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-github"],
    requiresAuth: true,
    authType: "token",
    authEnvVar: "GITHUB_TOKEN",
    documentation: "https://github.com/modelcontextprotocol/servers",
    icon: "🐙",
    tags: ["git", "code", "repository", "issues", "pull-requests"],
    popular: true,
  },
  {
    id: "postgres",
    name: "PostgreSQL",
    description: "Query and manage PostgreSQL databases",
    category: "database",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-postgres"],
    requiresAuth: true,
    authType: "api-key",
    authEnvVar: "POSTGRES_CONNECTION_STRING",
    icon: "🐘",
    tags: ["database", "sql", "postgres"],
    popular: true,
  },
  {
    id: "sqlite",
    name: "SQLite",
    description: "Query and manage SQLite databases",
    category: "database",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-sqlite", "--db-path", "./data.db"],
    icon: "🗃️",
    tags: ["database", "sql", "sqlite", "local"],
    popular: true,
  },
  {
    id: "brave-search",
    name: "Brave Search",
    description: "Web search using Brave Search API",
    category: "ai",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-brave-search"],
    requiresAuth: true,
    authType: "api-key",
    authEnvVar: "BRAVE_API_KEY",
    documentation: "https://brave.com/search/api/",
    icon: "🦁",
    tags: ["search", "web", "internet"],
    popular: true,
  },
  {
    id: "puppeteer",
    name: "Puppeteer",
    description: "Browser automation and web scraping",
    category: "code",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-puppeteer"],
    icon: "🎭",
    tags: ["browser", "automation", "scraping", "testing"],
    popular: true,
  },
  {
    id: "memory",
    name: "Memory",
    description: "Persistent memory and knowledge graph",
    category: "ai",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-memory"],
    icon: "🧠",
    tags: ["memory", "knowledge", "graph", "persistence"],
    popular: true,
  },
  {
    id: "fetch",
    name: "Fetch",
    description: "Fetch web pages and convert to markdown",
    category: "productivity",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-fetch"],
    icon: "🌐",
    tags: ["web", "fetch", "markdown", "scraping"],
    popular: true,
  },
  {
    id: "sequential-thinking",
    name: "Sequential Thinking",
    description: "Dynamic problem-solving through structured thoughts",
    category: "ai",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-sequential-thinking"],
    icon: "🔄",
    tags: ["thinking", "reasoning", "problem-solving"],
    popular: true,
  },
  {
    id: "slack",
    name: "Slack",
    description: "Interact with Slack workspaces",
    category: "productivity",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-slack"],
    requiresAuth: true,
    authType: "token",
    authEnvVar: "SLACK_BOT_TOKEN",
    icon: "💬",
    tags: ["chat", "messaging", "team"],
  },
  {
    id: "google-drive",
    name: "Google Drive",
    description: "Access and manage Google Drive files",
    category: "cloud",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-gdrive"],
    requiresAuth: true,
    authType: "oauth",
    icon: "📂",
    tags: ["cloud", "storage", "google", "files"],
  },
  {
    id: "notion",
    name: "Notion",
    description: "Read and write Notion pages and databases",
    category: "productivity",
    transport: "stdio",
    command: "npx",
    args: ["-y", "notion-mcp-server"],
    requiresAuth: true,
    authType: "api-key",
    authEnvVar: "NOTION_API_KEY",
    icon: "📝",
    tags: ["notes", "database", "wiki", "productivity"],
  },
  {
    id: "sentry",
    name: "Sentry",
    description: "Monitor errors and issues from Sentry",
    category: "code",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-sentry"],
    requiresAuth: true,
    authType: "token",
    authEnvVar: "SENTRY_AUTH_TOKEN",
    icon: "🐛",
    tags: ["errors", "monitoring", "debugging"],
  },
  {
    id: "aws-kb-retrieval",
    name: "AWS Knowledge Base",
    description: "Query AWS Bedrock Knowledge Bases",
    category: "cloud",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-aws-kb-retrieval"],
    requiresAuth: true,
    authType: "api-key",
    authEnvVar: "AWS_ACCESS_KEY_ID",
    icon: "☁️",
    tags: ["aws", "cloud", "knowledge", "rag"],
  },
  {
    id: "everart",
    name: "EverArt",
    description: "Generate images with AI",
    category: "ai",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-everart"],
    requiresAuth: true,
    authType: "api-key",
    authEnvVar: "EVERART_API_KEY",
    icon: "🎨",
    tags: ["image", "generation", "art", "ai"],
  },

  // ============ CLAUDE / ANTHROPIC COMMON ============
  {
    id: "context7",
    name: "Context7",
    description: "Up-to-date documentation for any library",
    category: "code",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@upstash/context7-mcp"],
    icon: "📚",
    tags: ["documentation", "libraries", "api"],
    popular: true,
  },
  {
    id: "serena",
    name: "Serena",
    description: "Semantic code tools for intelligent editing",
    category: "code",
    transport: "stdio",
    command: "npx",
    args: ["-y", "serena-mcp-server"],
    icon: "🔮",
    tags: ["code", "semantic", "refactoring", "symbols"],
  },
  {
    id: "magic-21st",
    name: "21st.dev Magic",
    description: "UI component builder and inspiration",
    category: "code",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@21st-dev/magic-mcp"],
    icon: "✨",
    tags: ["ui", "components", "react", "design"],
  },

  // ============ SECURITY ============
  {
    id: "vault",
    name: "HashiCorp Vault",
    description: "Secrets management with Vault",
    category: "security",
    transport: "stdio",
    command: "npx",
    args: ["-y", "mcp-server-vault"],
    requiresAuth: true,
    authType: "token",
    authEnvVar: "VAULT_TOKEN",
    icon: "🔐",
    tags: ["secrets", "security", "vault"],
  },

  // ============ FROM CLAUDE DESKTOP CONFIG ============
  {
    id: "huggingface",
    name: "Hugging Face",
    description: "Access Hugging Face models, datasets, and Spaces",
    category: "ai",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@huggingface/mcp-client"],
    requiresAuth: true,
    authType: "token",
    authEnvVar: "HF_TOKEN",
    documentation: "https://huggingface.co/settings/tokens",
    icon: "🤗",
    tags: ["ai", "models", "datasets", "inference", "huggingface"],
    popular: true,
  },
  {
    id: "google-maps",
    name: "Google Maps",
    description: "Geocoding, directions, and places via Google Maps API",
    category: "cloud",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-google-maps"],
    requiresAuth: true,
    authType: "api-key",
    authEnvVar: "GOOGLE_MAPS_API_KEY",
    icon: "🗺️",
    tags: ["maps", "geocoding", "directions", "places", "google"],
  },
  {
    id: "twitter",
    name: "Twitter/X",
    description: "Post tweets, search, and manage Twitter/X account",
    category: "productivity",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-twitter"],
    requiresAuth: true,
    authType: "api-key",
    authEnvVar: "TWITTER_BEARER_TOKEN",
    icon: "𝕏",
    tags: ["twitter", "social", "posting", "search"],
  },

  // ============ WIDGETDC / CYBERSTREAMS ============
  {
    id: "cyberstreams",
    name: "Cyberstreams MCP",
    description: "Cyberstreams hybrid AI platform tools",
    category: "widgetdc",
    transport: "stdio",
    command: "node",
    args: ["C:\\Users\\claus\\cyberstreams-hybrid\\build\\local\\src\\mcp-server.js"],
    icon: "🌊",
    tags: ["cyberstreams", "widgetdc", "hybrid", "ai"],
    popular: true,
  },
  {
    id: "cyberstreams-cockpit",
    name: "Cyberstreams Cockpit",
    description: "Control panel for Cyberstreams - OAuth, secrets, system management",
    category: "widgetdc",
    transport: "http",
    url: "http://localhost:3456",
    icon: "🎛️",
    tags: ["cyberstreams", "cockpit", "oauth", "secrets", "management"],
  },
  {
    id: "widgetdc-neo4j",
    name: "WidgetDC Neo4j",
    description: "Neo4j graph database for WidgetDC knowledge graphs",
    category: "widgetdc",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@neo4j-contrib/mcp-neo4j"],
    requiresAuth: true,
    authType: "api-key",
    authEnvVar: "NEO4J_URI",
    icon: "🕸️",
    tags: ["widgetdc", "neo4j", "graph", "database", "knowledge"],
  },
  {
    id: "widgetdc-cloudflare",
    name: "WidgetDC Cloudflare Workers",
    description: "Cloudflare Workers integration for edge deployment",
    category: "widgetdc",
    transport: "http",
    url: "https://cyberstreams.clak.workers.dev",
    icon: "⚡",
    tags: ["widgetdc", "cloudflare", "workers", "edge", "serverless"],
  },

  // ============ LOCAL TOOLS ============
  {
    id: "sca-01-tools",
    name: "SCA-01 Tools",
    description: "Built-in SCA-01 file and make tools",
    category: "filesystem",
    transport: "stdio",
    command: "node",
    args: ["./build/mcp/toolServer.js"],
    icon: "🎯",
    tags: ["sca-01", "local", "tools"],
  },

  // ============ ADDITIONAL USEFUL SERVERS ============
  {
    id: "time",
    name: "Time",
    description: "Get current time in different timezones",
    category: "productivity",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-time"],
    icon: "🕐",
    tags: ["time", "timezone", "clock"],
  },
  {
    id: "docker",
    name: "Docker",
    description: "Manage Docker containers and images",
    category: "code",
    transport: "stdio",
    command: "npx",
    args: ["-y", "mcp-server-docker"],
    icon: "🐳",
    tags: ["docker", "containers", "devops"],
  },
  {
    id: "kubernetes",
    name: "Kubernetes",
    description: "Manage Kubernetes clusters and resources",
    category: "cloud",
    transport: "stdio",
    command: "npx",
    args: ["-y", "mcp-server-kubernetes"],
    requiresAuth: true,
    authType: "token",
    authEnvVar: "KUBECONFIG",
    icon: "☸️",
    tags: ["kubernetes", "k8s", "devops", "cloud"],
  },
  {
    id: "redis",
    name: "Redis",
    description: "Redis database operations",
    category: "database",
    transport: "stdio",
    command: "npx",
    args: ["-y", "mcp-server-redis"],
    requiresAuth: true,
    authType: "api-key",
    authEnvVar: "REDIS_URL",
    icon: "🔴",
    tags: ["redis", "cache", "database", "nosql"],
  },
  {
    id: "mongodb",
    name: "MongoDB",
    description: "MongoDB database operations and queries",
    category: "database",
    transport: "stdio",
    command: "npx",
    args: ["-y", "mcp-server-mongodb"],
    requiresAuth: true,
    authType: "api-key",
    authEnvVar: "MONGODB_URI",
    icon: "🍃",
    tags: ["mongodb", "nosql", "database"],
  },
  {
    id: "azure-devops",
    name: "Azure DevOps",
    description: "Azure DevOps pipelines, repos, and work items",
    category: "code",
    transport: "stdio",
    command: "npx",
    args: ["-y", "mcp-server-azure-devops"],
    requiresAuth: true,
    authType: "token",
    authEnvVar: "AZURE_DEVOPS_PAT",
    icon: "🔷",
    tags: ["azure", "devops", "ci-cd", "microsoft"],
  },
  {
    id: "jira",
    name: "Jira",
    description: "Jira issue tracking and project management",
    category: "productivity",
    transport: "stdio",
    command: "npx",
    args: ["-y", "mcp-server-jira"],
    requiresAuth: true,
    authType: "api-key",
    authEnvVar: "JIRA_API_TOKEN",
    icon: "📋",
    tags: ["jira", "issues", "project-management", "atlassian"],
  },
  {
    id: "confluence",
    name: "Confluence",
    description: "Confluence wiki pages and spaces",
    category: "productivity",
    transport: "stdio",
    command: "npx",
    args: ["-y", "mcp-server-confluence"],
    requiresAuth: true,
    authType: "api-key",
    authEnvVar: "CONFLUENCE_API_TOKEN",
    icon: "📝",
    tags: ["confluence", "wiki", "documentation", "atlassian"],
  },
  {
    id: "linear",
    name: "Linear",
    description: "Linear issue tracking for modern teams",
    category: "productivity",
    transport: "stdio",
    command: "npx",
    args: ["-y", "mcp-server-linear"],
    requiresAuth: true,
    authType: "api-key",
    authEnvVar: "LINEAR_API_KEY",
    icon: "📐",
    tags: ["linear", "issues", "project-management"],
  },
  {
    id: "openai",
    name: "OpenAI",
    description: "OpenAI GPT models and DALL-E",
    category: "ai",
    transport: "stdio",
    command: "npx",
    args: ["-y", "mcp-server-openai"],
    requiresAuth: true,
    authType: "api-key",
    authEnvVar: "OPENAI_API_KEY",
    icon: "🧠",
    tags: ["openai", "gpt", "dall-e", "ai"],
  },
  {
    id: "anthropic",
    name: "Anthropic Claude",
    description: "Anthropic Claude AI models",
    category: "ai",
    transport: "stdio",
    command: "npx",
    args: ["-y", "mcp-server-anthropic"],
    requiresAuth: true,
    authType: "api-key",
    authEnvVar: "ANTHROPIC_API_KEY",
    icon: "🤖",
    tags: ["anthropic", "claude", "ai"],
  },
  {
    id: "youtube",
    name: "YouTube",
    description: "YouTube video info, transcripts, and search",
    category: "productivity",
    transport: "stdio",
    command: "npx",
    args: ["-y", "mcp-server-youtube"],
    requiresAuth: true,
    authType: "api-key",
    authEnvVar: "YOUTUBE_API_KEY",
    icon: "📺",
    tags: ["youtube", "video", "transcripts"],
  },
  {
    id: "email",
    name: "Email (SMTP)",
    description: "Send emails via SMTP",
    category: "productivity",
    transport: "stdio",
    command: "npx",
    args: ["-y", "mcp-server-email"],
    requiresAuth: true,
    authType: "api-key",
    authEnvVar: "SMTP_PASSWORD",
    icon: "📧",
    tags: ["email", "smtp", "notifications"],
  },
  {
    id: "calendar",
    name: "Google Calendar",
    description: "Google Calendar events and scheduling",
    category: "productivity",
    transport: "stdio",
    command: "npx",
    args: ["-y", "mcp-server-google-calendar"],
    requiresAuth: true,
    authType: "oauth",
    icon: "📅",
    tags: ["calendar", "google", "scheduling", "events"],
  },
  {
    id: "todoist",
    name: "Todoist",
    description: "Todoist task management",
    category: "productivity",
    transport: "stdio",
    command: "npx",
    args: ["-y", "mcp-server-todoist"],
    requiresAuth: true,
    authType: "api-key",
    authEnvVar: "TODOIST_API_TOKEN",
    icon: "✅",
    tags: ["todoist", "tasks", "productivity"],
  },
  {
    id: "stripe",
    name: "Stripe",
    description: "Stripe payments and subscriptions",
    category: "cloud",
    transport: "stdio",
    command: "npx",
    args: ["-y", "mcp-server-stripe"],
    requiresAuth: true,
    authType: "api-key",
    authEnvVar: "STRIPE_SECRET_KEY",
    icon: "💳",
    tags: ["stripe", "payments", "billing"],
  },
  {
    id: "supabase",
    name: "Supabase",
    description: "Supabase database, auth, and storage",
    category: "database",
    transport: "stdio",
    command: "npx",
    args: ["-y", "mcp-server-supabase"],
    requiresAuth: true,
    authType: "api-key",
    authEnvVar: "SUPABASE_SERVICE_ROLE_KEY",
    icon: "⚡",
    tags: ["supabase", "postgres", "auth", "storage"],
  },
  {
    id: "playwright",
    name: "Playwright",
    description: "Browser testing and automation with Playwright",
    category: "code",
    transport: "stdio",
    command: "npx",
    args: ["-y", "mcp-server-playwright"],
    icon: "🎭",
    tags: ["playwright", "testing", "browser", "automation"],
  },
];

// ============ HELPER FUNCTIONS ============

export function getServersByCategory(category: McpCategory): McpServerDefinition[] {
  return MCP_SERVER_CATALOG.filter(s => s.category === category);
}

export function getPopularServers(): McpServerDefinition[] {
  return MCP_SERVER_CATALOG.filter(s => s.popular);
}

export function searchServers(query: string): McpServerDefinition[] {
  const q = query.toLowerCase();
  return MCP_SERVER_CATALOG.filter(s => 
    s.name.toLowerCase().includes(q) ||
    s.description.toLowerCase().includes(q) ||
    s.tags?.some(t => t.toLowerCase().includes(q))
  );
}

export function getServerById(id: string): McpServerDefinition | undefined {
  return MCP_SERVER_CATALOG.find(s => s.id === id);
}

export function getCategoryLabel(category: McpCategory): string {
  const labels: Record<McpCategory, string> = {
    filesystem: "📁 Filesystem",
    code: "💻 Code & Dev",
    database: "🗄️ Database",
    ai: "🤖 AI & ML",
    productivity: "📋 Productivity",
    cloud: "☁️ Cloud",
    security: "🔐 Security",
    widgetdc: "🔧 WidgetDC",
    custom: "⚙️ Custom",
  };
  return labels[category];
}

export function getAllCategories(): McpCategory[] {
  return ["filesystem", "code", "database", "ai", "productivity", "cloud", "security", "widgetdc", "custom"];
}

